### PR TITLE
python 3 compatibility

### PR DESCRIPTION
**Pull request by kennethreitz**

### CODE REVIEW

**Comment by kennethreitz** [comment]
oh this is a dupe of https://github.com/core-api/python-jsonhyperschema-codec/pull/8

**Comment by kennethreitz** [comment]
can we get this released? this is a big blocker for me.

**Comment by lovelydinosaur** [comment]
Resolved via #8. Released as 1.0.3.

👍

**Comment by kennethreitz** [comment]
\o/

**Pull request closed without merging**
